apiVersion: v1
kind: Service
metadata:
  name: sws-api
spec:
  selector:
    app: sws
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: sws-web
spec:
  selector:
    app: sws
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: sws
  ports:
    - port: 3306
  clusterIP: None
