-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 17:20:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sws
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sws
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sws` DEFAULT CHARACTER SET utf8 ;
USE `sws` ;

-- -----------------------------------------------------
-- Table `sws`.`celebrities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`celebrities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `video_price` DECIMAL(9,2) NULL,
  `urgent_price` DECIMAL(9,2) NULL,
  `event_price` DECIMAL(9,2) NULL,
  `short_desc` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  `video` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `other_name` VARCHAR(45) NULL,
  `instructions` TEXT NOT NULL,
  `video` VARCHAR(255) NULL,
  `celebrities_id` INT NOT NULL,
  `status` ENUM('PENDING', 'REJECTED', 'APPROVED', 'CANCELED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
  `uploaded_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_celebrities_idx` (`celebrities_id` ASC) ,
  CONSTRAINT `fk_videos_celebrities`
    FOREIGN KEY (`celebrities_id`)
    REFERENCES `sws`.`celebrities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `website` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `event_date` TIMESTAMP NOT NULL,
  `description` TEXT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `celebrities_id` INT NOT NULL,
  `locations_id` INT NOT NULL,
  `status` ENUM('PENDING', 'REJECTED', 'CHANGED', 'APPROVED', 'CANCELED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
  PRIMARY KEY (`id`),
  INDEX `fk_events_celebrities1_idx` (`celebrities_id` ASC) ,
  INDEX `fk_events_locations1_idx` (`locations_id` ASC) ,
  CONSTRAINT `fk_events_celebrities1`
    FOREIGN KEY (`celebrities_id`)
    REFERENCES `sws`.`celebrities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `sws`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`ads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(255) NOT NULL,
  `instructions` TEXT NOT NULL,
  `photo` VARCHAR(255) NULL,
  `celebrities_id` INT NOT NULL,
  `status` ENUM('PENDING', 'REJECTED', 'CHANGED', 'APPROVED', 'CANCELED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
  `type` ENUM('TV', 'DEGITAL') NOT NULL DEFAULT 'DEGITAL',
  `working_days` TINYINT NOT NULL DEFAULT 1,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  `director` VARCHAR(45) NULL,
  `locations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ads_celebrities1_idx` (`celebrities_id` ASC) ,
  INDEX `fk_ads_locations1_idx` (`locations_id` ASC) ,
  CONSTRAINT `fk_ads_celebrities1`
    FOREIGN KEY (`celebrities_id`)
    REFERENCES `sws`.`celebrities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ads_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `sws`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `urgent` TINYINT NULL DEFAULT 0,
  `price` DECIMAL(2) NOT NULL,
  `users_id` INT NOT NULL,
  `request_id` INT NOT NULL,
  `request_type` ENUM('videos', 'ads', 'events') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) ,
  INDEX `fk_orders_request1_idx` (`request_id` ASC) ,
  UNIQUE INDEX `request_type_id_UNIQUE` (`request_type` ASC, `request_id` ASC) ,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sws`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_videos1`
    FOREIGN KEY (`request_id`)
    REFERENCES `sws`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_events1`
    FOREIGN KEY (`request_id`)
    REFERENCES `sws`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_ads1`
    FOREIGN KEY (`request_id`)
    REFERENCES `sws`.`ads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sws`.`celebrities_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sws`.`celebrities_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `celebrities_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_celebrities_categories_celebrities1_idx` (`celebrities_id` ASC) ,
  INDEX `fk_celebrities_categories_categories1_idx` (`categories_id` ASC) ,
  UNIQUE INDEX `celebrities_id_UNIQUE` (`celebrities_id` ASC, `categories_id` ASC) ,
  CONSTRAINT `fk_celebrities_categories_celebrities1`
    FOREIGN KEY (`celebrities_id`)
    REFERENCES `sws`.`celebrities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_celebrities_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `sws`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
